databases:
  - name: chess_masterclass
    databaseName: chess_masterclass
    user: Propsowicz

services:
  - type: web
    name: chess_masterclass
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd chess_masterclass && gunicorn chess_masterclass.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
