databases:
  - name: chess_masterclass
    databaseName: chess_masterclass
    user: Propsowicz

services:
  - type: web
    name: chess_masterclass
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn chess_masterclass.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chess_masterclass
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4