# Generated by Django 4.0.6 on 2022-10-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomOrder',
        ),
    ]
