# Generated by Django 4.0.6 on 2022-10-25 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_delete_customorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotPayRespond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.CharField(max_length=99)),
                ('operation_status', models.CharField(max_length=99)),
                ('operation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('operation_datatime', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
