# Generated by Django 4.0.6 on 2022-10-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_dotpayrespond'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotpayrespond',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
