# Generated by Django 4.0.6 on 2022-10-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_dotpayrespond_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dotpayrespond',
            old_name='user',
            new_name='user_id',
        ),
    ]
