# Generated by Django 4.0.6 on 2022-10-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_user_dotpayrespond_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dotpayrespond',
            old_name='user_id',
            new_name='user',
        ),
    ]
