# Generated by Django 4.0.6 on 2022-10-28 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0006_rename_user_id_dotpayrespond_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotpayrespond',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_credit', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('isDone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
