# Generated by Django 4.0.6 on 2022-10-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chesscourse_premiumplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chesscourse')),
            ],
        ),
    ]
