# Generated by Django 4.0.6 on 2022-10-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_chesscourse_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesscourse',
            name='liked_by',
        ),
    ]
