# Generated by Django 4.0.6 on 2022-10-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_chesscourse_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesscourse',
            name='representationChessBoard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
