# Generated by Django 4.0.6 on 2022-10-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_course_chessstudytable_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessstudy',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
