# Generated by Django 4.0.6 on 2022-10-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_chessstudy_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessstudytable',
            name='coord',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='chesstable',
            name='coord',
            field=models.CharField(max_length=600),
        ),
    ]
