# Generated by Django 4.0.6 on 2022-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_chessstudytable_coord_alter_chesstable_coord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesscourse',
            name='representationChessBoard',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='chessstudy',
            name='representationChessBoard',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
