# Generated by Django 4.0.6 on 2022-10-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
