# Generated by Django 4.1.1 on 2022-09-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_user_edit_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_edit_keys',
            name='url',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
