# Generated by Django 4.1.1 on 2022-09-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_user_edit_keys_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_edit_keys',
            name='secretkey',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
